name: Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release
        
      - name: Syntax Check
        run: dotnet build --no-restore --configuration Release /p:WarningLevel=4 /p:TreatWarningsAsErrors=true
