name: Auth Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Framework
      run: |
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-runtime-4.7.2
    - name: Restore dependencies
      run: dotnet restore TestProj
    - name: Build
      run: dotnet build TestProj --no-restore
    - name: Test
      run: dotnet test TestProj --no-build --verbosity normal
