name: Auth Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2'
        
    - name: Restore dependencies
      run: dotnet restore TestProj
    - name: Build
      run: dotnet build TestProj --no-restore
    - name: Test
      run: dotnet test TestProj --no-build --verbosity normal
